/* SOMENTE o array 'exercises' */
const exercises = [
  {
    id: 1,
    name: 'Supino Reto',
    muscle: 'Peitoral',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Clássico para peitoral maior. Execução no banco horizontal com barra.',
  },
  {
    id: 2,
    name: 'Agachamento Livre',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Movimento completo de membros inferiores e core com barra nas costas.',
  },
  {
    id: 3,
    name: 'Levantamento Terra',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Exercício de cadeia posterior; trabalha costas, glúteos e posteriores.',
  },
  {
    id: 4,
    name: 'Desenvolvimento Militar',
    muscle: 'Ombros',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Press vertical acima da cabeça focando deltoides e tríceps.',
  },
  {
    id: 5,
    name: 'Barra Fixa',
    muscle: 'Costas',
    equipment: 'Peso corporal',
    difficulty: 'Intermediário',
    desc: 'Puxada na barra com peso corporal; ênfase em latíssimos e bíceps.',
  },
  {
    id: 6,
    name: 'Remada Curvada',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Puxada horizontal para espessura das costas e força de dorsal.',
  },
  {
    id: 7,
    name: 'Supino Inclinado',
    muscle: 'Peitoral',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Variação inclinada para foco no peitoral superior.',
  },
  {
    id: 8,
    name: 'Supino com Halteres',
    muscle: 'Peitoral',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Versão com halteres que aumenta amplitude e estabilidade.',
  },
  {
    id: 9,
    name: 'Agachamento Frontal',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Barra na frente; maior ênfase em quadríceps e core.',
  },
  {
    id: 10,
    name: 'Terra Romeno (Stiff)',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Hinge de quadril para isquiotibiais e glúteos com joelhos semiestendidos.',
  },
  {
    id: 11,
    name: 'Rosca Direta',
    muscle: 'Bíceps',
    equipment: 'Barra',
    difficulty: 'Iniciante',
    desc: 'Flexão de cotovelos com barra para bíceps.',
  },
  {
    id: 12,
    name: 'Tríceps Testa',
    muscle: 'Tríceps',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Extensão de tríceps deitado isolando a cabeça longa.',
  },
  {
    id: 13,
    name: 'Puxada na Frente (Pulldown)',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Puxada vertical na polia simulando barra fixa.',
  },
  {
    id: 14,
    name: 'Crucifixo com Halteres',
    muscle: 'Peitoral',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Abertura lateral no banco para alongar e contrair o peitoral.',
  },
  {
    id: 15,
    name: 'Elevação Lateral',
    muscle: 'Ombros',
    equipment: 'Halteres',
    difficulty: 'Iniciante',
    desc: 'Isolamento do deltoide médio para largura dos ombros.',
  },
  {
    id: 16,
    name: 'Remada Baixa',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Puxada horizontal em polia baixa para espessura dorsal.',
  },
  {
    id: 17,
    name: 'Leg Press 45',
    muscle: 'Pernas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Empurrar plataforma com as pernas; alto controle de carga.',
  },
  {
    id: 18,
    name: 'Agachamento no Smith',
    muscle: 'Pernas',
    equipment: 'Smith',
    difficulty: 'Iniciante',
    desc: 'Agachamento guiado para foco em quadríceps e segurança.',
  },
  {
    id: 19,
    name: 'Cadeira Extensora',
    muscle: 'Pernas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Extensão isolada de quadríceps.',
  },
  {
    id: 20,
    name: 'Mesa Flexora',
    muscle: 'Pernas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Flexão de joelhos para isquiotibiais.',
  },
  {
    id: 21,
    name: 'Puxada Neutra na Polia',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Pulldown com pegada neutra para dorsais e bíceps.',
  },
  {
    id: 22,
    name: 'Crucifixo Inclinado',
    muscle: 'Peitoral',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Abertura no banco inclinado focando peitoral superior.',
  },
  {
    id: 23,
    name: 'Rosca Martelo',
    muscle: 'Bíceps',
    equipment: 'Halteres',
    difficulty: 'Iniciante',
    desc: 'Pegada neutra para braquial e braquiorradial.',
  },
  {
    id: 24,
    name: 'Tríceps Corda na Polia',
    muscle: 'Tríceps',
    equipment: 'Cabo',
    difficulty: 'Iniciante',
    desc: 'Extensão de tríceps em polia alta com corda.',
  },
  {
    id: 25,
    name: 'Remada Cavalinho (T-Bar)',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Remada com barra ancorada para espessura dorsal.',
  },
  {
    id: 26,
    name: 'Encolhimento com Barra',
    muscle: 'Trapézio',
    equipment: 'Barra',
    difficulty: 'Iniciante',
    desc: 'Elevação de ombros para trapézios.',
  },
  {
    id: 27,
    name: 'Elevação Frontal',
    muscle: 'Ombros',
    equipment: 'Halteres',
    difficulty: 'Iniciante',
    desc: 'Isolamento do deltoide anterior.',
  },
  {
    id: 28,
    name: 'Face Pull',
    muscle: 'Ombros',
    equipment: 'Cabo',
    difficulty: 'Iniciante',
    desc: 'Remada alta para deltóide posterior e manguito.',
  },
  {
    id: 29,
    name: 'Passada (Lunge)',
    muscle: 'Pernas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Avanços alternados trabalhando quadríceps e glúteos.',
  },
  {
    id: 30,
    name: 'Afundo Búlgaro',
    muscle: 'Pernas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Unilateral com pé de trás elevado; foco em glúteos e quadríceps.',
  },
  {
    id: 31,
    name: 'Hip Thrust',
    muscle: 'Glúteos',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Elevação de quadril apoiado em banco para glúteos.',
  },
  {
    id: 32,
    name: 'Glute Bridge',
    muscle: 'Glúteos',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Ponte de glúteos no chão; pode ser carregada.',
  },
  {
    id: 33,
    name: 'Puxada Atrás (Lat Pulldown Atrás)',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Variação por trás da cabeça (usar com cautela).',
  },
  {
    id: 34,
    name: 'Remada Unilateral no Banco (Serrote)',
    muscle: 'Costas',
    equipment: 'Halteres',
    difficulty: 'Iniciante',
    desc: 'Remada com um halter apoiando o joelho no banco.',
  },
  {
    id: 35,
    name: 'Crossover no Cabo',
    muscle: 'Peitoral',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Crucifixo em pé na polia, com grande amplitude.',
  },
  {
    id: 36,
    name: 'Pull-over com Halter',
    muscle: 'Peitoral',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Movimento de extensão do ombro; trabalha peitoral e serrátil.',
  },
  {
    id: 37,
    name: 'Remada Alta',
    muscle: 'Ombros',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Puxada na vertical para deltoides e trapézio.',
  },
  {
    id: 38,
    name: 'Desenvolvimento com Halteres',
    muscle: 'Ombros',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Press acima da cabeça com halteres.',
  },
  {
    id: 39,
    name: 'Rosca Alternada',
    muscle: 'Bíceps',
    equipment: 'Halteres',
    difficulty: 'Iniciante',
    desc: 'Flexão de cotovelo alternando os braços.',
  },
  {
    id: 40,
    name: 'Rosca Scott',
    muscle: 'Bíceps',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Rosca apoiada no banco Scott para maior isolamento.',
  },
  {
    id: 41,
    name: 'Tríceps Francês',
    muscle: 'Tríceps',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Extensão acima da cabeça com halter único ou dois halteres.',
  },
  {
    id: 42,
    name: 'Paralela (Dips)',
    muscle: 'Peitoral',
    equipment: 'Peso corporal',
    difficulty: 'Intermediário',
    desc: 'Mergulho nas paralelas; ênfase em peitoral e tríceps.',
  },
  {
    id: 43,
    name: 'Remada Sentada na Máquina',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Remada com pegadas variadas para dorsal.',
  },
  {
    id: 44,
    name: 'Puxada Triângulo (Close-Grip Pulldown)',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Pegada fechada para maior ativação de dorsais.',
  },
  {
    id: 45,
    name: 'Agachamento Sumô',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Pegada e base amplas; maior foco em adutores e glúteos.',
  },
  {
    id: 46,
    name: 'Levantamento Terra Sumô',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Variação sumô do terra com base aberta.',
  },
  {
    id: 47,
    name: 'Good Morning',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Hinge de quadril para lombar e isquios; exige técnica.',
  },
  {
    id: 48,
    name: 'Panturrilha em Pé',
    muscle: 'Panturrilhas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Elevação de gêmeos de pé.',
  },
  {
    id: 49,
    name: 'Panturrilha Sentado',
    muscle: 'Panturrilhas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Elevação de gêmeos sentado, foco no sóleo.',
  },
  {
    id: 50,
    name: 'Step-up no Banco',
    muscle: 'Pernas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Subida no banco unilateral para quadríceps e glúteos.',
  },
  {
    id: 51,
    name: 'Abdominal Crunch',
    muscle: 'Abdômen',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Flexão da coluna para reto abdominal.',
  },
  {
    id: 52,
    name: 'Prancha',
    muscle: 'Abdômen',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Isometria de core mantendo o corpo alinhado.',
  },
  {
    id: 53,
    name: 'Abdominal Infra',
    muscle: 'Abdômen',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Elevação de pernas para reto inferior e flexores de quadril.',
  },
  {
    id: 54,
    name: 'Ab Wheel (Roda Abdominal)',
    muscle: 'Abdômen',
    equipment: 'Acessório',
    difficulty: 'Intermediário',
    desc: 'Extensão com roda para grande ativação de core.',
  },
  {
    id: 55,
    name: 'Pullover na Máquina',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Movimento de extensão do ombro focando dorsais.',
  },
  {
    id: 56,
    name: 'Remada na Máquina Hammer',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Remada unilateral guiada com alavanca.',
  },
  {
    id: 57,
    name: 'Crucifixo no Peck-Deck',
    muscle: 'Peitoral',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Abertura guiada com máquina para peitoral.',
  },
  {
    id: 58,
    name: 'Supino Declinado',
    muscle: 'Peitoral',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Variação declinada enfatizando peitoral inferior.',
  },
  {
    id: 59,
    name: 'Desenvolvimento Arnold',
    muscle: 'Ombros',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Press com rotação iniciado em supinação.',
  },
  {
    id: 60,
    name: 'Remada Invertida',
    muscle: 'Costas',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Puxada na barra baixa com corpo em prancha.',
  },
  {
    id: 61,
    name: 'Pullover com Barra',
    muscle: 'Peitoral',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Variação do pullover com barra reta.',
  },
  {
    id: 62,
    name: 'Rosca 21',
    muscle: 'Bíceps',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Método com parciais e repetições completas para bíceps.',
  },
  {
    id: 63,
    name: 'Tríceps Testa com Halteres',
    muscle: 'Tríceps',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Extensão deitado segurando dois halteres.',
  },
  {
    id: 64,
    name: 'Tríceps Coice',
    muscle: 'Tríceps',
    equipment: 'Halteres',
    difficulty: 'Iniciante',
    desc: 'Extensão de cotovelo com tronco inclinado.',
  },
  {
    id: 65,
    name: 'Rosca Concentrada',
    muscle: 'Bíceps',
    equipment: 'Halteres',
    difficulty: 'Iniciante',
    desc: 'Isolamento unilateral apoiando o braço na coxa.',
  },
  {
    id: 66,
    name: 'Rosca no Cabo',
    muscle: 'Bíceps',
    equipment: 'Cabo',
    difficulty: 'Iniciante',
    desc: 'Rosca contínua com polia baixa.',
  },
  {
    id: 67,
    name: 'Crucifixo no Cabo Alta',
    muscle: 'Peitoral',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Crossover alto para ênfase no peitoral inferior.',
  },
  {
    id: 68,
    name: 'Crucifixo no Cabo Baixa',
    muscle: 'Peitoral',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Crossover baixo para peitoral superior.',
  },
  {
    id: 69,
    name: 'Puxada atrás com Triângulo',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Puxada vertical com pegada neutra por trás (cautela).',
  },
  {
    id: 70,
    name: 'Elevação de Quadril no Banco',
    muscle: 'Glúteos',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Versão sem carga do hip thrust.',
  },
  {
    id: 71,
    name: 'Abdução de Quadril',
    muscle: 'Glúteos',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Empurra as pernas para fora focando glúteo médio.',
  },
  {
    id: 72,
    name: 'Adutora',
    muscle: 'Pernas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Fecha as pernas contra resistência para adutores.',
  },
  {
    id: 73,
    name: 'Remada no Smith',
    muscle: 'Costas',
    equipment: 'Smith',
    difficulty: 'Iniciante',
    desc: 'Remada horizontal guiada para estabilidade.',
  },
  {
    id: 74,
    name: 'Desenvolvimento no Smith',
    muscle: 'Ombros',
    equipment: 'Smith',
    difficulty: 'Iniciante',
    desc: 'Press guiado acima da cabeça.',
  },
  {
    id: 75,
    name: 'Puxada na Frente com Barra T',
    muscle: 'Costas',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Variação de T-Bar com suporte.',
  },
  {
    id: 76,
    name: "Farmer's Walk",
    muscle: 'Antebraços',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Caminhada carregando cargas pesadas para pegada e core.',
  },
  {
    id: 77,
    name: 'Kettlebell Swing',
    muscle: 'Pernas',
    equipment: 'Kettlebell',
    difficulty: 'Intermediário',
    desc: 'Hinge explosivo para glúteos e condicionamento.',
  },
  {
    id: 78,
    name: 'Clean and Press (técnico)',
    muscle: 'Total',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Movimento olímpico com potência e coordenação.',
  },
  {
    id: 79,
    name: 'Remada Pendlay',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Remada partindo do chão a cada repetição.',
  },
  {
    id: 80,
    name: 'Good Morning com Halteres',
    muscle: 'Pernas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Hinge leve para posterior e lombar.',
  },
  {
    id: 81,
    name: 'Rosca Inversa',
    muscle: 'Antebraços',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Rosca com pegada pronada focando braquiorradial.',
  },
  {
    id: 82,
    name: 'Prancha Lateral',
    muscle: 'Abdômen',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Isometria lateral para oblíquos.',
  },
  {
    id: 83,
    name: 'Abdominal na Polia (Crunch no Cabo)',
    muscle: 'Abdômen',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Flexão de tronco ajoelhado usando a polia alta.',
  },
  {
    id: 84,
    name: 'Levantamento de Pernas na Barra',
    muscle: 'Abdômen',
    equipment: 'Peso corporal',
    difficulty: 'Intermediário',
    desc: 'Elevação de pernas pendurado para reto inferior.',
  },
  {
    id: 85,
    name: 'Remada Meadows',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Remada unilateral com barra ancorada e tronco inclinado.',
  },
  {
    id: 86,
    name: 'Shrug com Halteres',
    muscle: 'Trapézio',
    equipment: 'Halteres',
    difficulty: 'Iniciante',
    desc: 'Encolhimento de ombros com halteres.',
  },
  {
    id: 87,
    name: 'Rosca Spider',
    muscle: 'Bíceps',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Rosca apoiado no banco inclinado para pico do bíceps.',
  },
  {
    id: 88,
    name: 'Skull Crusher com Barra EZ',
    muscle: 'Tríceps',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Variação mais confortável para punhos.',
  },
  {
    id: 89,
    name: 'Overhead Press com Kettlebell',
    muscle: 'Ombros',
    equipment: 'Kettlebell',
    difficulty: 'Intermediário',
    desc: 'Press unilateral que exige estabilidade de core.',
  },
  {
    id: 90,
    name: 'Z-Press',
    muscle: 'Ombros',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Press sentado no chão, alta exigência de core e mobilidade.',
  },
  {
    id: 91,
    name: 'Jefferson Curl',
    muscle: 'Posterior',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Flexão segmentada da coluna para mobilidade e força leve.',
  },
  {
    id: 92,
    name: 'Nordic Curl Assistido',
    muscle: 'Posterior',
    equipment: 'Acessório',
    difficulty: 'Avançado',
    desc: 'Flexão excêntrica de joelhos para isquiotibiais.',
  },
  {
    id: 93,
    name: 'Cadeira Abdutora Inversa (Glute Drive)',
    muscle: 'Glúteos',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Máquina específica para glúteo máximo com cinto.',
  },
  {
    id: 94,
    name: 'Walking Lunge',
    muscle: 'Pernas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Passadas caminhando contínuas.',
  },
  {
    id: 95,
    name: 'Pistol Squat (assistido)',
    muscle: 'Pernas',
    equipment: 'Peso corporal',
    difficulty: 'Avançado',
    desc: 'Agachamento unilateral profundo com controle.',
  },
  {
    id: 96,
    name: 'Landmine Press',
    muscle: 'Ombros',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Press angular com barra ancorada (landmine).',
  },
  {
    id: 97,
    name: 'Remada Landmine Unilateral',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Puxada unilateral na base landmine.',
  },
  {
    id: 98,
    name: 'Dead Bug',
    muscle: 'Abdômen',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Controle de core alternando braços e pernas.',
  },
  {
    id: 99,
    name: 'Hollow Hold',
    muscle: 'Abdômen',
    equipment: 'Peso corporal',
    difficulty: 'Intermediário',
    desc: 'Isometria com coluna neutra para estabilização.',
  },
  {
    id: 100,
    name: 'Good Morning na Smith',
    muscle: 'Posterior',
    equipment: 'Smith',
    difficulty: 'Intermediário',
    desc: 'Variação guiada do good morning para controle.',
  },
  {
    id: 101,
    name: 'Agachamento Hack',
    muscle: 'Pernas',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Agachamento guiado com foco em quadríceps e estabilidade da coluna.',
  },
  {
    id: 102,
    name: 'Box Squat',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Agachamento sentado em caixa para controle de profundidade e potência.',
  },
  {
    id: 103,
    name: 'Zercher Squat',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Barra apoiada na dobra do cotovelo; grande exigência de core e quadríceps.',
  },
  {
    id: 104,
    name: 'Sissy Squat',
    muscle: 'Pernas',
    equipment: 'Acessório',
    difficulty: 'Intermediário',
    desc: 'Isolamento de quadríceps com grande alavanca de joelho.',
  },
  {
    id: 105,
    name: 'Pause Squat',
    muscle: 'Pernas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Agachamento com pausa no fundo para força e controle.',
  },
  {
    id: 106,
    name: 'Split Squat com Elevação Frontal do Pé',
    muscle: 'Pernas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Unilateral com pé dianteiro elevado para aumentar a amplitude.',
  },
  {
    id: 107,
    name: 'Reverse Lunge',
    muscle: 'Pernas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Passada para trás com maior estabilidade do joelho.',
  },
  {
    id: 108,
    name: 'Curtsy Lunge',
    muscle: 'Glúteos',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Passada cruzada enfatizando glúteo médio e adutores.',
  },
  {
    id: 109,
    name: 'Step-up Lateral',
    muscle: 'Pernas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Subida lateral no banco para adutores e glúteos.',
  },
  {
    id: 110,
    name: 'Agachamento no Smith',
    muscle: 'Pernas',
    equipment: 'Smith',
    difficulty: 'Iniciante',
    desc: 'Agachamento guiado para foco em quadríceps e segurança.',
  },
  {
    id: 111,
    name: 'Elevação Pelvicano Smith',
    muscle: 'Glúteos',
    equipment: 'Smith',
    difficulty: 'Intermediário',
    desc: 'Elevação de quadril com trajetória guiada.',
  },
  {
    id: 112,
    name: 'Supino no Smith',
    muscle: 'Peitoral',
    equipment: 'Smith',
    difficulty: 'Iniciante',
    desc: 'Press horizontal com barra guiada para estabilidade.',
  },
  {
    id: 113,
    name: 'Supino Máquina (Chest Press)',
    muscle: 'Peitoral',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Pressão horizontal guiada para peitoral e tríceps.',
  },
  {
    id: 114,
    name: 'Press Inclinado na Máquina',
    muscle: 'Peitoral',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Variação inclinada guiada focando peitoral superior.',
  },
  {
    id: 115,
    name: 'Supino Declinado com Halteres',
    muscle: 'Peitoral',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Press com halteres enfatizando porção inferior do peitoral.',
  },
  {
    id: 116,
    name: 'Flexão de Braço (Push-up)',
    muscle: 'Peitoral',
    equipment: 'Peso corporal',
    difficulty: 'Iniciante',
    desc: 'Empurrar o corpo do chão; trabalho de peitoral, ombros e tríceps.',
  },
  {
    id: 117,
    name: 'Flexão com Carga',
    muscle: 'Peitoral',
    equipment: 'Acessório',
    difficulty: 'Intermediário',
    desc: 'Variação de flexão com peso extra no dorso.',
  },
  {
    id: 118,
    name: 'Peck-Deck Reverso',
    muscle: 'Ombros',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Abertura reversa para deltóide posterior e romboides.',
  },
  {
    id: 119,
    name: 'Fly no Cabo (altura média)',
    muscle: 'Peitoral',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Crucifixo na polia com peitorais na linha do ombro.',
  },
  {
    id: 120,
    name: 'Elevação Lateral no Cabo',
    muscle: 'Ombros',
    equipment: 'Cabo',
    difficulty: 'Iniciante',
    desc: 'Isolamento com tensão contínua no deltoide médio.',
  },
  {
    id: 121,
    name: 'Elevação Lateral na Máquina',
    muscle: 'Ombros',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Variação guiada para estabilidade e foco.',
  },
  {
    id: 122,
    name: 'Y-Raise no Banco Inclinado',
    muscle: 'Ombros',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Elevação em Y para deltóide posterior e serrátil.',
  },
  {
    id: 123,
    name: 'Cuban Press',
    muscle: 'Ombros',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Rotação externa + press para manguito e deltoides.',
  },
  {
    id: 124,
    name: 'Press Militar Sentado com Halteres',
    muscle: 'Ombros',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Press acima da cabeça com suporte do banco.',
  },
  {
    id: 125,
    name: 'Remada Alta no Cabo',
    muscle: 'Ombros',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Puxada vertical guiada para deltoides e trapézio.',
  },
  {
    id: 126,
    name: 'Remada Unilateral no Cabo',
    muscle: 'Costas',
    equipment: 'Cabo',
    difficulty: 'Iniciante',
    desc: 'Serrote na polia com tensão constante.',
  },
  {
    id: 127,
    name: 'Seal Row (Remada no Banco Reto)',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Remada com tronco apoiado, reduzindo balanço.',
  },
  {
    id: 128,
    name: 'Remada Apoiada no Banco Inclinado',
    muscle: 'Costas',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Chest-supported row para espessura dorsal.',
  },
  {
    id: 129,
    name: 'Remada Yates',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Remada com pegada supinada e tronco mais ereto.',
  },
  {
    id: 130,
    name: 'Pulldown com Braços Estendidos',
    muscle: 'Costas',
    equipment: 'Cabo',
    difficulty: 'Iniciante',
    desc: 'Extensão do ombro na polia para latíssimos (straight-arm).',
  },
  {
    id: 131,
    name: 'Pulldown Unilateral',
    muscle: 'Costas',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Puxada vertical com um braço por vez.',
  },
  {
    id: 132,
    name: 'Pulldown Supinado Unilateral',
    muscle: 'Costas',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Variação com pegada supinada para latíssimos e bíceps.',
  },
  {
    id: 133,
    name: 'Rack Pull',
    muscle: 'Costas',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Terra parcial com a barra elevada no rack para lombar e trapézio.',
  },
  {
    id: 134,
    name: 'Terra no Déficit',
    muscle: 'Posterior',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Deadlift em plataforma para maior amplitude.',
  },
  {
    id: 135,
    name: 'Terra Romeno com Halteres',
    muscle: 'Posterior',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Hinge com halteres focando isquiotibiais e glúteos.',
  },
  {
    id: 136,
    name: 'Elevação Pelvicana na Máquina',
    muscle: 'Glúteos',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Versão guiada do Elevação Pelvicapara glúteos.',
  },
  {
    id: 137,
    name: 'Coice de Glúteo no Cabo',
    muscle: 'Glúteos',
    equipment: 'Cabo',
    difficulty: 'Iniciante',
    desc: 'Extensão de quadril em pé com tornozeleira.',
  },
  {
    id: 138,
    name: 'Abdução de Quadril no Cabo',
    muscle: 'Glúteos',
    equipment: 'Cabo',
    difficulty: 'Iniciante',
    desc: 'Afastar a perna para ativar glúteo médio.',
  },
  {
    id: 139,
    name: 'Glute Ham Raise (GHR)',
    muscle: 'Posterior',
    equipment: 'Acessório',
    difficulty: 'Avançado',
    desc: 'Flexão de joelho e extensão de quadril excêntrica na máquina GHR.',
  },
  {
    id: 140,
    name: 'Reverse Hyper',
    muscle: 'Posterior',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Extensão de quadril com ênfase em glúteos e lombar.',
  },
  {
    id: 141,
    name: 'Back Extension 45º',
    muscle: 'Lombar',
    equipment: 'Banco 45º',
    difficulty: 'Iniciante',
    desc: 'Hiperextensão para lombar e cadeia posterior.',
  },
  {
    id: 142,
    name: 'Panturrilha no Leg Press',
    muscle: 'Panturrilhas',
    equipment: 'Máquina',
    difficulty: 'Iniciante',
    desc: 'Elevação de panturrilhas usando a plataforma do leg press.',
  },
  {
    id: 143,
    name: 'Donkey Calf Raise',
    muscle: 'Panturrilhas',
    equipment: 'Máquina',
    difficulty: 'Intermediário',
    desc: 'Elevação com tronco inclinado para alongamento extra.',
  },
  {
    id: 144,
    name: 'Panturrilha no Smith',
    muscle: 'Panturrilhas',
    equipment: 'Smith',
    difficulty: 'Iniciante',
    desc: 'Elevação em pé usando barra guiada.',
  },
  {
    id: 145,
    name: 'Rosca no Banco Inclinado',
    muscle: 'Bíceps',
    equipment: 'Halteres',
    difficulty: 'Intermediário',
    desc: 'Rosca com alongamento máximo do bíceps.',
  },
  {
    id: 146,
    name: 'Rosca com Barra W',
    muscle: 'Bíceps',
    equipment: 'Barra',
    difficulty: 'Iniciante',
    desc: 'Pegada mais confortável para punhos.',
  },
  {
    id: 147,
    name: 'Rosca Martelo na Corda',
    muscle: 'Bíceps',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Variação na polia para braquial e antebraço.',
  },
  {
    id: 148,
    name: 'Tríceps Invertido na Polia',
    muscle: 'Tríceps',
    equipment: 'Cabo',
    difficulty: 'Intermediário',
    desc: 'Pushdown com pegada supinada (reverse grip) para foco medial.',
  },
  {
    id: 149,
    name: 'JM Press',
    muscle: 'Tríceps',
    equipment: 'Barra',
    difficulty: 'Avançado',
    desc: 'Entre close-grip e skull crusher; foco em tríceps.',
  },
  {
    id: 150,
    name: 'Press Fechado no Banco (Close-Grip Bench)',
    muscle: 'Tríceps',
    equipment: 'Barra',
    difficulty: 'Intermediário',
    desc: 'Supino com pegada fechada enfatizando tríceps.',
  },
];
